FROM ubuntu:18.04


WORKDIR /

RUN apt update

RUN apt install curl -y

RUN curl -O https://download.litecoin.org/litecoin-0.16.3/linux/litecoin-0.16.3-x86_64-linux-gnu.tar.gz

RUN tar -zxvf litecoin-0.16.3-x86_64-linux-gnu.tar.gz

RUN mv litecoin-0.16.3 litecoin

RUN export PATH=$PATH:/litecoin/bin

ENV PATH="/litecoin/bin:${PATH}"
