FROM scrapinghub/scrapinghub-stack-scrapy:1.5-py3-latest
ENV TERM xterm
ENV SCRAPY_SETTINGS_MODULE tutorial.settings
RUN mkdir -p /app
WORKDIR /app

RUN apt install python3-dev -y

# Chrome browser and driver installation
WORKDIR /tmp

RUN apt-get install libxss1 libappindicator1 libindicator7 -y

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

RUN dpkg -i google-chrome*.deb; exit 0

RUN apt-get install -f -y

RUN apt-get install xvfb -y

RUN apt-get install unzip -y

RUN wget -N https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip

RUN unzip chromedriver_linux64.zip

RUN chmod +x chromedriver

RUN mv -f chromedriver /usr/local/share/chromedriver

RUN ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

RUN ln -s /usr/local/share/chromedriver /usr/bin/chromedriver



WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python setup.py install
