FROM scrapinghub/scrapinghub-stack-scrapy:1.3
ENV TERM xterm
ENV SCRAPY_SETTINGS_MODULE tutorial.settings


# Python 3.7
RUN apt update && apt upgrade

RUN apt install build-essential

RUN apt install libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev

RUN apt install libssl-dev libncurses5-dev libsqlite3-dev libreadline-dev libtk8.5 libgdm-dev libdb4o-cil-dev libpcap-dev


RUN apt install zlib1g

WORKDIR /tmp

RUN wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz

RUN tar -xzvf Python-3.7.0.tgz

RUN ./configure --enable-optimizations

RUN make

RUN make install



RUN mkdir -p /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python setup.py install
